### ISSUE TITLE
Value "Code: 210. DB::NetException: Connection refused: (localhost:9000, 127.0.0.1)" of type "string" is not suitable for value type "Numeric (float)"

### ISSUE THREAD

**Issue by denisgolius** [Altinity/clickhouse-zabbix-template#13]
![screenshot 7](https://user-images.githubusercontent.com/5650611/45959149-e0a28080-c021-11e8-9c93-95730c20c175.png)
There is a problem for both types of **Numeric** .

Zabbix  Server 3.4.11
Zabbix  Client 3.4.14
Server Ubuntu Server 18.04
ufw allow to connect from 127.0.0.1 to port 9000

**Comment by Vladimir0Beliaev** [comment]
Here you need to look at the rights to the clickhouse server

**Comment by Slach** [comment]
@denisgolius please check your clickhouse connections settings 
try run on zabbix-agent/clickhouse host
```
bash -x /path/to/zbx_clickhouse_monitor.sh "Uptime" "localhost" "--user default --connect_timeout 5 --receive_timeout 5"
```

also you can try run on zabbix-server
```
zabbix-get -s your-zabbix-agent-server-dns-or-ip -k ch_params[Uptime]
```
