### ISSUE TITLE
Problem with some counters

### ISSUE THREAD

**Issue by Vladimir0Beliaev** [Altinity/clickhouse-zabbix-template#14]
I can't get values for these counters
![screenshot_20181116_160516](https://user-images.githubusercontent.com/45100212/48626393-6d324500-e9ba-11e8-9151-500a996e3a02.png)
![screenshot_20181116_160530](https://user-images.githubusercontent.com/45100212/48626392-6c99ae80-e9ba-11e8-9300-0cad0fc80e41.png)
![screenshot_20181116_160544](https://user-images.githubusercontent.com/45100212/48626391-6c99ae80-e9ba-11e8-81ed-2515dcb68698.png)

**Comment by MasterGroosha** [comment]
Where did you get this list? ch_params[...] ?

**Comment by Slach** [comment]
@Vladimir0Beliaev unfortunately not all metrics have an initial value when `clickhouse-server` start
for example SelectedParts only get only if you make SELECT queries to tables with *MergreTree engine
