### ISSUE TITLE
17 Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by rmalenko** [Altinity/clickhouse-zabbix-template#16]
Hello,

Zabbix doesn't get data from the clickhouse server. If I run the command in server console 
`zabbix_get -s clickhouse-001-01 -k "ch_params[Uptime]"`

I have got the error message
`/etc/zabbix/scripts/zbx_clickhouse_monitor.sh: 17: /etc/zabbix/scripts/zbx_clickhouse_monitor.sh: Syntax error: "(" unexpected`

P.S.
The template doesn't have any graphs.

Regards,
Rostyslav

**Comment by denisgolius** [comment]
> Hello,
> 
> Zabbix doesn't get data from the clickhouse server. If I run the command in server console
> `zabbix_get -s clickhouse-001-01 -k "ch_params[Uptime]"`
> 
> I have got the error message
> `/etc/zabbix/scripts/zbx_clickhouse_monitor.sh: 17: /etc/zabbix/scripts/zbx_clickhouse_monitor.sh: Syntax error: "(" unexpected`
> 
> P.S.
> The template doesn't have any graphs.
> 
> Regards,
> Rostyslav

On ubuntu try this
`sudo apt-get install libxml2-utils`

**Comment by rmalenko** [comment]
Thank you.
