### ISSUE TITLE
zbx_clickhouse_monitor.sh: Syntax error: "(" unexpected" of type "string" is not suitable for value type "Numeric (unsigned)"

### ISSUE THREAD

**Issue by EmPRio93** [Altinity/clickhouse-zabbix-template#21]
![Снимок экрана от 2020-03-06 15-35-20](https://user-images.githubusercontent.com/55250036/76066466-4093a980-5fc0-11ea-85d4-896be3d34693.png)

**Comment by Slach** [comment]
@EmPRio93 could you show content your `/etc/zabbix/zabbix_agent.conf` and `/etc/zabbix/zabbix_agent.conf.d/` ?

**Comment by Slach** [comment]
confirmed, i reproduce it on my local environment
try to fix 
@alz, @sunsingerus JFYI

**Comment by Slach** [comment]
@EmPRio93 please look at https://github.com/Altinity/clickhouse-zabbix-template/blob/reanimate_zabbix/zbx_clickhouse_agent.example.conf

use `bash` instead of `sh` should solve your problem

**Comment by EmPRio93** [comment]
@Slach, thanks that works.
