### ISSUE TITLE
xmllist shown in error instead of xmllint in zbx_clickhouse_monitor.sh

### ISSUE THREAD

**Issue by ZizzyZizzy** [Altinity/clickhouse-zabbix-template#26]
I seriously wasted 15 minutes trying to find xmllist for Linux while scratching my head.

The test is for **xmllint**, the error output says **xmllist**.

CH_PATH="$(xmllint --xpath 'string(/yandex/path)' /etc/clickhouse-server/config.xml)"
if [ "$?" -ne 0 ]; then
	echo "Something went wrong with parsing ClickHouse config. Is xmllist installed? Is ClickHouse config available?"
	exit 1
fi

**Comment by Slach** [comment]
thanks a lot for reporting

**Comment by Slach** [comment]
fixed on https://github.com/Altinity/clickhouse-zabbix-template/commit/6e5a38c67b4936568f255ceb349f4d1c2138e1df

also you can try to use official Zabbix 5 clickhouse integration
